spring.application.name=integradora_trackontract
# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trackontract
spring.datasource.username=postgres
spring.datasource.password=root

# Dialecto de Hibernate para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Propiedades
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Ver queries en consola
spring.jpa.show-sql=true

#SpringSecurity
application.security.jwt.secret-key=MjAxMjM0NTY3ODkwMTIzNDU2Nzg5MA45DQwMTIzNDU2Nzg5MAwMTIzNDU2Nzg5MA
application.security.jwt.expiration-time=86400000
application.security.jwt.refresh-token-expiration-time=604800000
